# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       libsmack

# >> macros
# << macros

Summary:    SMACK Libraries
Version:    2.0.0
Release:    1
Group:      System/Base
License:    LGPLv2
URL:        http://meego.gitorious.org/meego-platform-security
Source0:    %{name}-%{version}.tar.bz2
Source100:  libsmack.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(check)
BuildRequires:  libattr-devel
BuildRequires:  uthash-devel
BuildRequires:  doxygen

%description
These are the userland libraries and tools for SMACK.


%package devel
Summary:    Development files for SMACK userland tools
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development headers for SMACK userland tools.


%package docs
Summary:    Documentation for SMACK userland tools
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description docs
Documentation for SMACK userland tools.


%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libsmack.so.1
%{_libdir}/libsmack.so.1.0.0
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libsmack.so
%{_includedir}/sys/smack.h
# << files devel

%files docs
%defattr(-,root,root,-)
# >> files docs
%{_docdir}/libsmack/libsmack-doxygen-*.tar.gz
# << files docs
